# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RainyShinyCloudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'

  # Pods for RainyShinyCloudy

  target 'RainyShinyCloudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RainyShinyCloudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
